### ISSUE TITLE
LibSass does not support expanded output

### ISSUE THREAD

**Issue by HugoGiraudel** [HugoGiraudel/sass-compatibility#17]

**Comment by xzyfer** [comment]
This is supported in Libsass@3.2.0 beta :)

**Comment by HugoGiraudel** [comment]
Unfortunately, SassMeister doesn't show `@error` anymore in the output (as it used to do), so I cannot update Sass Compatibility until it's fixed. 

Apparently, it's a LibSass/node-sass issue. See latest issue on their repo (can't link right now).

**Comment by HugoGiraudel** [comment]
There: https://github.com/jedfoster/SassMeister/issues/144.
