### ISSUE TITLE
Add sourcemaps

### ISSUE THREAD

**Issue by HugoGiraudel** [HugoGiraudel/sass-compatibility#31]

**Comment by xzyfer** [comment]
I'm not sure this can be asserted accurately. If you figure it out though the Libsass team would love to know how you did so :)

**Comment by HugoGiraudel** [comment]
As far as I can tell, I cannot assert this.

**Comment by xzyfer** [comment]
It looks like @snugug does this in gulp-sass https://github.com/sass/libsass/issues/1056 :)

**Comment by Snugug** [comment]
[This is how we test for sourcemaps](https://github.com/dlmanning/gulp-sass/blob/2.x/test/main.js#L170-L198)

Basically, we're not checking the contents of the mappings themselves, but rather that sourcemaps exist and the expected sources are in fact there.
